/**
 * Provenance markers for compliance exports built from illustrative data.
 *
 * A `MockDataBadge` on screen does not travel with a downloaded file. These exports title
 * themselves "EU AI Act Article 53 Compliance Document" and "NAIC UNFAIR DISCRIMINATION
 * TESTING REPORT", write a real filename to the user's disk, and leave the browser — at
 * which point nothing distinguishes them from a document assembled from measured results.
 * Every figure in them currently comes from a module-level constant.
 *
 * The wording lives here rather than being inlined three times so a regulatory disclaimer
 * cannot drift between the artifacts it applies to. Three call sites share it today:
 * UnfairDiscriminationTesting's filing report, and GpaiModelCard's text and JSON exports.
 *
 * When one of these views is wired to measured data, the export should stop calling these
 * helpers rather than have their text softened — a partially-real report is still not a
 * filing, and the honest move at that point is a per-field provenance column.
 */

/**
 * Shared wording primitives, so a PDF cover page, a DOCX paragraph, a CSV first row and a
 * plain-text banner all carry the SAME sentence. Rendered formats cannot reuse the text
 * blocks below (they need per-line layout control), and the failure mode of letting each
 * exporter phrase its own disclaimer is that they drift apart.
 */
export const SAMPLE_TITLE = 'SAMPLE - ILLUSTRATIVE DATA - NOT FOR REGULATORY FILING';

/** Short mark for a repeated page footer, where the full title will not fit. */
export const SAMPLE_FOOTER_MARK = 'SAMPLE - illustrative data - not for filing';

/** The body of the disclaimer, one array entry per line, for callers that lay out lines. */
export function sampleBannerLines(subject: string): string[] {
  return [
    `This document was generated by the AVA governance platform as a SAMPLE of the`,
    `following artifact:`,
    `    ${subject}`,
    `The figures in it are illustrative values held in the application source, not`,
    `measurements taken from a model, a dataset, or a production system.`,
    'Do not submit this document to a regulator, an auditor, or a counterparty.',
    'Do not cite any figure in it as evidence of compliance.',
  ];
}

/** Banner for a plain-text report. Goes at the very top, before the report's own title. */
export function sampleExportBanner(subject: string): string {
  const bar = '='.repeat(72);
  return [
    bar,
    SAMPLE_TITLE,
    bar,
    '',
    'This document was generated by the AVA governance platform as a SAMPLE of the',
    'following artifact:',
    '',
    `    ${subject}`,
    '',
    'The figures below are illustrative values held in the application source, not',
    'measurements taken from a model, a dataset, or a production system.',
    '',
    'Do not submit this document to a regulator, an auditor, or a counterparty.',
    'Do not cite any figure in it as evidence of compliance.',
    '',
    bar,
    '',
    '',
  ].join('\n');
}

/** Closing restatement, so the marking survives someone reading only the end of the file. */
export function sampleExportFooter(): string {
  const bar = '='.repeat(72);
  return [
    '',
    '',
    bar,
    'END OF SAMPLE DOCUMENT',
    '',
    'Reminder: every figure above is illustrative sample data, not a measurement.',
    'This document is not a regulatory filing and must not be submitted as one.',
    bar,
    '',
  ].join('\n');
}

/**
 * Marks the downloaded filename itself. A file that reaches a shared drive is usually
 * identified by its name long before anyone opens it.
 */
export function sampleFilename(base: string, extension: string): string {
  return `SAMPLE_NOT_FOR_FILING_${base}.${extension}`;
}

/**
 * Envelope for a JSON export. A raw object serialization carries no banner at all, so the
 * marking has to be a field — placed first so it is visible without scrolling, and
 * duplicated in a name a schema validator would reject if this were mistaken for real input.
 */
export function sampleJsonEnvelope(subject: string, payload: unknown): string {
  return JSON.stringify(
    {
      _WARNING: 'SAMPLE - ILLUSTRATIVE DATA - NOT FOR REGULATORY FILING',
      _description:
        `Illustrative sample of the ${subject} produced by the AVA governance platform. ` +
        'Every value under `data` is a constant held in the application source, not a ' +
        'measurement. Do not submit this file to a regulator or cite it as evidence of ' +
        'compliance.',
      _isSampleData: true,
      data: payload,
    },
    null,
    2,
  );
}
