import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

// FSI Foundry use-case UI build.
//
// Backend + governance URLs are provided at runtime via runtime-config.json
// (generated by the Foundry UI deploy), NOT via a Vite dev proxy — so no proxy
// is needed for the deployed build. The optional dev proxy below only activates
// when VITE_DEV_PROXY_TARGET is set, for local standalone development.
//
// base: './' keeps asset URLs relative so the SPA works behind CloudFront.
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  const basePath = env.VITE_BASE_PATH || './'
  const devProxyTarget = env.VITE_DEV_PROXY_TARGET || ''

  return {
    base: basePath,
    plugins: [react()],
    build: {
      outDir: 'dist',
      sourcemap: false,
      target: ['es2020', 'chrome90', 'firefox90', 'safari14'],
    },
    ...(devProxyTarget
      ? {
          server: {
            proxy: {
              '/api': {
                target: devProxyTarget,
                changeOrigin: true,
                secure: false,
              },
            },
          },
        }
      : {}),
  }
})
