#!/bin/bash
set -euo pipefail

echo "=== Market Surveillance Deployment ==="

# Read parameters from tfvars if present (generated by the packaging service)
if [ -f deploy.auto.tfvars.json ]; then
  export AWS_REGION=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('aws_region','us-east-1'))")
  DEPLOY_NAME=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('project_name','market-surveillance'))")
else
  DEPLOY_NAME="market-surveillance"
fi

ENVIRONMENT="dev"
echo "Deployment name: $DEPLOY_NAME"
echo "Environment: $ENVIRONMENT"
echo "Region: $AWS_REGION"

# Remove auto-generated tfvars to avoid "undeclared variable" warnings in Terraform
# (the packaging service generates project_name/aws_region but Market Surveillance doesn't use them)
rm -f deploy.auto.tfvars.json
rm -f infrastructure/foundations/deploy.auto.tfvars.json
rm -f infrastructure/app-infra/deploy.auto.tfvars.json

# Prerequisite (one-time, account-level): The Terraform module creates an
# aws_cloudwatch_log_delivery.traces resource that routes AgentCore traces
# through X-Ray → CloudWatch Logs. That pipeline requires the account's X-Ray
# trace segment destination to be "CloudWatchLogs" AND a CloudWatch Logs
# resource policy granting xray.amazonaws.com write access to aws/spans.
# Neither can be done by this script at deploy time — CodeBuild's service
# role doesn't have xray:UpdateTraceSegmentDestination or logs:PutResourcePolicy.
#
# Operators must run these commands ONCE per account/region before the first
# deploy (the UI surfaces the same instructions in a prerequisites banner):
#
#   aws logs put-resource-policy --policy-name AWSServiceRoleForXRayLogs \
#     --policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow",
#     "Principal":{"Service":"xray.amazonaws.com"},"Action":"logs:PutLogEvents",
#     "Resource":"arn:aws:logs:REGION:ACCOUNT:log-group:aws/spans:*"}]}'
#
#   aws xray update-trace-segment-destination --destination CloudWatchLogs \
#     --region REGION

# Step 1: Deploy backend infrastructure (Terraform foundations + app-infra)
echo "=== Step 1/3: Deploying backend infrastructure ==="
chmod +x scripts/*.sh 2>/dev/null || true

# Bridge AVA control-plane env vars into TF_VAR_* so the foundations layer
# picks them up when it configures the CloudFront viewer-request Function.
# When these are empty (standalone laptop deploy without AVA), the CloudFront
# module skips the AVA SSO Function entirely and the custom Cognito login
# page keeps working — zero regression for standalone deploys.
export TF_VAR_fsi_app_signing_secret="${AVA_FSI_APP_SIGNING_SECRET:-}"
export TF_VAR_ava_ui_login_url="${AVA_UI_LOGIN_URL:-}"

scripts/deploy-backend.sh --environment "$ENVIRONMENT" --auto-approve || {
  echo "ERROR: Backend infrastructure deployment failed"
  exit 1
}

# Step 2: Deploy webapp (Docker build + push + ASG refresh)
echo "=== Step 2/3: Deploying web application ==="
scripts/deploy-webapp-ec2.sh --environment "$ENVIRONMENT" || {
  echo "ERROR: Web application deployment failed"
  exit 1
}

# Step 3: Seed Database via in-VPC Lambda
# ─────────────────────────────────────────────────────────────────────────
# The DB seeder is a Lambda inside Aurora's VPC (see
# infrastructure/modules/db-seeder). It reads DB creds from Secrets Manager
# and runs the existing seeding_scripts package in-process:
#   1. Table-count idempotency probe — skips if the schema already exists.
#   2. `db_ops.db_init` creates the schema from schema.yaml.
#   3. `data_gen` generates synthetic CSVs into /tmp.
#   4. `database_seeding.seed` loads the CSVs in FK order.
#
# Replaces the previous CodeBuild-via-SSM-port-forward path, which
# silently skipped seeding whenever the tunnel didn't open (port-forward
# depends on `nc`, `session-manager-plugin`, and CodeBuild IAM perms —
# any one missing quietly turned seeding into a no-op while the build
# still reported success).
#
# Fail-loud contract:
#   - If the Lambda name isn't in Terraform outputs → fail.
#   - If `aws lambda invoke` returns non-zero → fail.
#   - If the Lambda response contains "errorMessage" → fail.
#   - Only "seeded" or "already_seeded" in the response body counts as
#     success. Anything else aborts Step 3.
echo "=== Step 3/3: Seeding database (via in-VPC Lambda) ==="

SEEDER_NAME=$(cd infrastructure/app-infra && terraform output -raw db_seeder_lambda_name 2>/dev/null || true)
if [ -z "$SEEDER_NAME" ]; then
  echo "ERROR: db_seeder_lambda_name not found in app-infra terraform outputs."
  echo "       The db-seeder module may not have applied — check Step 1 logs."
  exit 1
fi
echo "  Seeder: $SEEDER_NAME"

# Response written to /tmp/seed-response.json. `aws lambda invoke` sets
# FunctionError=Handled/Unhandled if the Lambda raised; we surface that
# and fail explicitly. Timeouts and network errors also propagate.
SEED_RESPONSE=/tmp/seed-response.json
rm -f "$SEED_RESPONSE"

INVOKE_META=$(aws lambda invoke \
  --function-name "$SEEDER_NAME" \
  --region "$AWS_REGION" \
  --payload '{}' \
  --cli-binary-format raw-in-base64-out \
  --log-type Tail \
  "$SEED_RESPONSE" \
  --output json 2>&1) || {
  echo "ERROR: aws lambda invoke failed:"
  echo "$INVOKE_META"
  exit 1
}

echo "  Invoke metadata: $INVOKE_META"
echo "  Response:"
cat "$SEED_RESPONSE"
echo ""

# Parse the response: success if it contains "seeded" or "already_seeded".
# Failure if it contains "errorMessage" (Lambda's convention for handled
# exceptions).
python3 - <<PY || { echo "ERROR: seeder returned failure — see response above."; exit 1; }
import json, sys
with open("$SEED_RESPONSE") as f:
    body = json.load(f)
if "errorMessage" in body:
    print(f"Seeder raised: {body.get('errorType')}: {body.get('errorMessage')}")
    sys.exit(1)
if body.get("already_seeded"):
    print(f"  Idempotent: DB already has {body.get('existing_tables', '?')} tables. Skipped seeding.")
    sys.exit(0)
if "seeded" in body:
    s = body["seeded"]
    rows = s.get("rows_loaded", {})
    print(f"  Seeded {s.get('tables_created', '?')} tables in {body.get('seconds', '?')}s")
    for tbl, n in rows.items():
        print(f"    {tbl}: {n} rows")
    sys.exit(0)
print(f"Unexpected seeder response shape: {body}")
sys.exit(1)
PY

echo "  ✓ Database seeding complete"

# Collect outputs
echo "=== Collecting deployment outputs ==="
python3 -c "
import boto3, json, os

region = os.environ.get('AWS_REGION', 'us-east-1')
env = '$ENVIRONMENT'
ssm = boto3.client('ssm', region_name=region)
outputs = {'deployment_id': os.environ.get('DEPLOYMENT_ID', ''), 'status': 'success'}

params_to_check = {
    'ui_url': f'/market-surveillance/{env}/foundations/cloudfront/domain',
    'api_endpoint': f'/market-surveillance/{env}/app-infra/api-gateway/endpoint',
    'cognito_user_pool_id': f'/market-surveillance/{env}/foundations/cognito/user-pool-id',
    'cognito_client_id': f'/market-surveillance/{env}/foundations/cognito/web-app-client-id',
    'cognito_hosted_ui': f'/market-surveillance/{env}/foundations/cognito/hosted-ui-url',
    'alb_dns': f'/market-surveillance/{env}/foundations/alb/dns-name',
}

# Create a default demo user in Cognito
try:
    user_pool_id = ssm.get_parameter(Name=f'/market-surveillance/{env}/foundations/cognito/user-pool-id')['Parameter']['Value']
    cognito = boto3.client('cognito-idp', region_name=region)
    demo_email = 'admin@example.com'
    demo_password = 'Demo1234!'
    try:
        cognito.admin_create_user(
            UserPoolId=user_pool_id,
            Username=demo_email,
            UserAttributes=[
                {'Name': 'email', 'Value': demo_email},
                {'Name': 'email_verified', 'Value': 'true'},
            ],
            TemporaryPassword=demo_password,
            MessageAction='SUPPRESS',
        )
        cognito.admin_set_user_password(
            UserPoolId=user_pool_id,
            Username=demo_email,
            Password=demo_password,
            Permanent=True,
        )
        outputs['demo_user'] = demo_email
        outputs['demo_password'] = demo_password
        print(f'Created demo user: {demo_email}')
    except cognito.exceptions.UsernameExistsException:
        outputs['demo_user'] = demo_email
        outputs['demo_password'] = demo_password
        print(f'Demo user already exists: {demo_email}')
except Exception as e:
    print(f'Warning: Could not create demo user: {e}')

for key, param_name in params_to_check.items():
    try:
        val = ssm.get_parameter(Name=param_name)['Parameter']['Value']
        if key == 'ui_url' and val:
            outputs[key] = f'https://{val}'
        else:
            outputs[key] = val
    except Exception:
        pass

json.dump(outputs, open('/tmp/outputs.json', 'w'))
print(f'Collected {len(outputs)} outputs')
print(json.dumps(outputs, indent=2))
" || { echo '{"deployment_id":"'${DEPLOYMENT_ID:-unknown}'","status":"success"}' > /tmp/outputs.json; }

echo "=== Deployment complete ==="
